# Additional Plugins:
plugins:
  - "prettier-plugin-java"

# Global Options for all files:
printWidth: 120
tabWidth: 4

# Overrides for certain file types:
overrides:
  - files:
      - "*.yaml"
      - "*.yml"
    options:
      tabWidth: 2
